version: "3"

services:
  wiki:
    build: .
    container_name: wiki
    ports:
      - "8000:80"
    environment:
      WIKI_ADMIN_USERNAME: admin
      WIKI_ADMIN_PASSWORD: admin
    volumes:
      - ./docker-data/db:/config/db
      - ./docker-data/media:/config/media
      - ./docker-data/static:/config/static
#      - ./docker-data/extra_settings.py:/the_wiki/the_wiki/extra_settings.py