version: "3"

services:
  wiki:
    image: ghcr.io/thetemptingsavior/docker-django-wiki:master
    build: .
    container_name: wiki
    ports:
      - "8000:80"
    environment:
      WIKI_ADMIN_USERNAME: admin
      WIKI_ADMIN_PASSWORD: admin
      # If set, will put auth in front of the entire wiki
      WIKI_AUTH_EVERYWHERE: "true"
      # WIKI_SECRET_KEY: "some-super-secret-keu"
      WIKI_DEBUG: "false"
      WIKI_LANGUAGE_CODE: "en-gb"
      WIKI_TIME_ZONE: "UTC"
    volumes:
      - ./docker-data/db:/config/db
      - ./docker-data/media:/config/media
      - ./docker-data/static:/config/static
#      - ./docker-data/extra_settings.py:/the_wiki/the_wiki/extra_settings.py