version: "3"

services:
  wiki:
    image: ghcr.io/thetemptingsavior/docker-django-wiki:master
    build: .
    container_name: wiki
    ports:
      - "8000:80"
    environment:
      WIKI_ADMIN_USERNAME: admin
      WIKI_ADMIN_PASSWORD: admin
      # If set, will put auth in front of the entire wiki
      WIKI_AUTH_EVERYWHERE: "true"
      # When set will add the templates path to list of directories to search for templates
      WIKI_CUSTOM_TEMPLATES: "false"
      # Default value is '/config/templates'
      WIKI_CUSTOM_TEMPLATES_PATH: "/config/templates"
    volumes:
      - ./docker-data/db:/config/db
      - ./docker-data/media:/config/media
      - ./docker-data/static:/config/static
#      - ./docker-data/extra_settings.py:/the_wiki/the_wiki/extra_settings.py