#!/usr/bin/with-contenv bash
# shellcheck shell=bash

echo "[svc-nginx] Starting nginx service"

if pgrep -f "[n]ginx:" >/dev/null; then
    echo "Zombie nginx processes detected, sending SIGTERM"
    pkill -ef [n]ginx:
    sleep 1
fi

if pgrep -f "[n]ginx:" >/dev/null; then
    echo "Zombie nginx processes still active, sending SIGKILL"
    pkill -9 -ef [n]ginx:
    sleep 1
fi

exec \
    s6-notifyoncheck -d -n 300 -w 1000 \
      /usr/sbin/nginx