name: Docker Build Test

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag docker-django-wiki-dev:$(date +%s)
      - name: Run django-wiki tests
        run: |
          docker run --rm -it \
              -v $PWD/django-wiki-tests.sh:/tests.sh \
              --entrypoint=bash \
              docker-django-wiki-dev:$(date +%s) \
              bash /tests.sh 
